PREFIX dpp: <https://example.org/dpp/>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT ?product ?name ?manufacturer ?manufacturerName WHERE {
  GRAPH ?graph {
    ?product a dpp:Smartphone ; dct:title ?name ; dpp:manufacturedBy ?manufacturer .
    ?manufacturer dct:title ?manufacturerName .
  }
}
