PREFIX dpp: <https://example.org/dpp/>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT DISTINCT ?product ?name ?carbonValue WHERE {
  GRAPH ?graph {
    ?product a dpp:Smartphone ; dct:title ?name ;
      dpp:hasCarbonFootprint/dpp:carbonValue ?carbonValue .
    FILTER(?carbonValue > 50)
  }
}
ORDER BY DESC(?carbonValue)
