PREFIX dpp: <https://example.org/dpp/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT DISTINCT ?supplier ?supplierName ?material ?materialName WHERE {
  GRAPH ?graph {
    ?material a dpp:Material ; dpp:materialType ?materialType ; dpp:suppliedBy ?supplier .
    ?materialType a dpp:CriticalRawMaterial .
    OPTIONAL { ?supplier dct:title ?supplierName }
    OPTIONAL { ?materialType skos:prefLabel ?materialName }
  }
}
